export const SET_PAGE = 'product@set_page'
export const PAGE_REQUEST = 'product@page_request'
export const PAGE_DONE = 'product@page_done'
export const SET_CATEGORY_ID = 'product@set_category_id'
export const SET_IMAGES = 'product@set_images'
export const SET_DETAIL = 'product@set_detail'